### ISSUE TITLE
Deprecated selector in `atom-gdb-debugger/styles/atom-gdb-debugger.less`

### ISSUE THREAD

**Issue by esden** [gsmcmullin/atom-gdb-debugger#10]
In `atom-gdb-debugger/styles/atom-gdb-debugger.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.atom-text-editor .line.gdb-frame,
:host .line.gdb-frame,
atom-text-editor .line.gdb-frame,
atom-text-editor::shadow .line.gdb-frame` => `.atom-text-editor .line.gdb-frame,
:host .line.gdb-frame,
atom-text-editor .line.gdb-frame,
atom-text-editor.editor .line.gdb-frame`

* `.atom-text-editor .line-number.gdb-bkpt .icon-right,
:host .line-number.gdb-bkpt .icon-right,
atom-text-editor .line-number.gdb-bkpt .icon-right,
atom-text-editor::shadow .line-number.gdb-bkpt .icon-right` => `.atom-text-editor .line-number.gdb-bkpt .icon-right,
:host .line-number.gdb-bkpt .icon-right,
atom-text-editor .line-number.gdb-bkpt .icon-right,
atom-text-editor.editor .line-number.gdb-bkpt .icon-right`

* `.atom-text-editor .line-number.gdb-bkpt .icon-right:before,
:host .line-number.gdb-bkpt .icon-right:before,
atom-text-editor .line-number.gdb-bkpt .icon-right:before,
atom-text-editor::shadow .line-number.gdb-bkpt .icon-right:before` => `.atom-text-editor .line-number.gdb-bkpt .icon-right:before,
:host .line-number.gdb-bkpt .icon-right:before,
atom-text-editor .line-number.gdb-bkpt .icon-right:before,
atom-text-editor.editor .line-number.gdb-bkpt .icon-right:before`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by gsmcmullin** [comment]
This is a backwards incompatible change in Atom 1.13 beta, so we'll need to wait for the release before fixing it.  Fixing it will make Atom 1.13 a requirement, it will not work on older versions.

**Comment by esden** [comment]
Atom is at 1.14 now, so we should correct this. :)
